version: "3"
services:
  storemanager:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
      args:
        NODE_ENV: development
    container_name: storemanager
    ports:
      - "8000:8000"
      - "9229:9229"
    env_file:
      - .env
    volumes:
      - "./src:/opt/ruelala/app/src"
      - "./config:/opt/ruelala/app/config"
      - "./test:/opt/ruelala/app/test"
    # depends_on:
    #   - ruecommerce
    command: ['npm', 'start']
  # ruecommerce:
  #   image: mysql:5.6
  #   container_name: ruecommerce
  #   restart: always
  #   ports:
  #     - "3306:3306"
  #   env_file:
  #     - .env
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=supersecret
  #   volumes:
  #     - "./docker/volumes/ruecommerce:/var/lib/mysql"
  #   logging:
  #     driver: "none"