version: "3.4"
services:
  storemanager:
    build:
      context: .
      target: dev
      args:
        NODE_ENV: development
    container_name: storemanager
    ports:
      - "8000:8000"
      - "9229:9229"
    env_file:
      - .env
    volumes:
      - "./src:/opt/ruelala/app/src"
      - "./config:/opt/ruelala/app/config"
      - "./test:/opt/ruelala/app/test"
